all:
	echo "Call make for array, vector, pq, queue, stack, set, or umap."
array:
	g++ array.cpp -std=c++11 -o run
	./run
vector:
	g++ vector.cpp -std=c++11 -o run
	./run
pq:
	g++ pq.cpp -std=c++11 -o run
	./run
queue:
	g++ queue.cpp -std=c++11 -o run
	./run
stack:
	g++ stack.cpp -std=c++11 -o run
	./run
set:
	g++ set.cpp -std=c++11 -o run
	./run
umap:
	g++ umap.cpp -std=c++11 -o run
	./run
